# Generated by Django 3.1 on 2023-01-15 21:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre_cli', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_cli', models.CharField(max_length=100, verbose_name='Apellido')),
                ('direccion_clie', models.CharField(max_length=250, verbose_name='Dirección')),
                ('celular_cli', models.IntegerField(verbose_name='Número contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ing_fi', models.DateField(auto_now_add=True, verbose_name='Fecha Ingreso')),
                ('total_fi', models.PositiveIntegerField(verbose_name='Total')),
                ('observaciones_fi', models.CharField(max_length=250, verbose_name='Observaciones')),
                ('estado_fi', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='HoraHombre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hh', models.CharField(max_length=50)),
                ('descripcion_hh', models.CharField(max_length=250, verbose_name='Descripción')),
                ('precio_hh', models.PositiveIntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut_trab', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre_trab', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_trab_pa', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_trab_ma', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('celular_trab', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(999999999)], verbose_name='Número Contacto')),
                ('tipo_trab', models.CharField(max_length=20, verbose_name='Clasificación')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente_vh', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca_vh', models.CharField(max_length=50, verbose_name='Marca')),
                ('cilindrada_vh', models.PositiveIntegerField(verbose_name='Cilindrada')),
                ('kilometraje_vh', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('rut_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.cliente', verbose_name='Rut Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sv', models.CharField(max_length=50, verbose_name='Nombre Servicio')),
                ('desc_sv', models.CharField(max_length=250, verbose_name='Descripción Servicio')),
                ('hrs_240', models.PositiveIntegerField(verbose_name='Valor < 240 cc')),
                ('hrs_500', models.PositiveIntegerField(verbose_name='Valor < 500 cc')),
                ('hrs_800', models.PositiveIntegerField(verbose_name='Valor < 800 cc')),
                ('hrs_810', models.PositiveIntegerField(verbose_name='Valor > 810 cc')),
                ('id_hh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.horahombre', verbose_name='ID Hora Hombre')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ing_ot', models.DateField(auto_now_add=True, verbose_name='Fecha Ingreso')),
                ('fecha_fin_ot', models.DateField(blank=True, null=True, verbose_name='Fecha Finalización')),
                ('id_fi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.ficha_ingreso', verbose_name='Ficha Ingreso')),
                ('rut_trab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.trabajador', verbose_name='Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_is', models.CharField(max_length=50, verbose_name='Nombre Insumo')),
                ('cantidad_is', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('id_fi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.ficha_ingreso', verbose_name='Id Ficha')),
            ],
        ),
        migrations.AddField(
            model_name='ficha_ingreso',
            name='patente_vh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.vehiculo', verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='ficha_ingreso',
            name='rut_cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.cliente', verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_f', models.CharField(max_length=50, verbose_name='Nombre Falla')),
                ('desc_f', models.CharField(max_length=250, verbose_name='Descripción Falla')),
                ('hora_hh_f', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(9999)], verbose_name='Horas Hombre')),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.orden_trabajo', verbose_name='Orden Trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_servicio', models.PositiveIntegerField(verbose_name='Precio servicio')),
                ('id_fi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.ficha_ingreso', verbose_name='Número de Ficha')),
                ('id_sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.servicio', verbose_name='Número de servicio')),
            ],
        ),
    ]
