# Generated by Django 4.1.5 on 2023-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_auto_20230115_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="tipo_sv",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Tipo Servicio"
            ),
        ),
    ]
