# Generated by Django 4.1.5 on 2023-01-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_vehiculo_modelo_vh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="modelo_vh",
            field=models.CharField(max_length=50, verbose_name="Modelo"),
        ),
    ]
