# Generated by Django 4.1.5 on 2023-01-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_alter_vehiculo_modelo_vh"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="mill_km_vh",
            field=models.CharField(
                choices=[(1, "Kilometros"), (2, "Millas")],
                default="Kilometros",
                max_length=50,
                verbose_name="Unidad de Medida",
            ),
        ),
    ]
