# Generated by Django 4.1.5 on 2023-01-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0007_vehiculo_mill_km_vh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="mill_km_vh",
            field=models.CharField(
                choices=[("mill", "Kilometros"), ("km", "Millas")],
                default="Kilometros",
                max_length=50,
                verbose_name="Unidad de Medida",
            ),
        ),
    ]
