# Generated by Django 4.1.5 on 2023-02-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0009_alter_vehiculo_mill_km_vh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="hrs_240",
            field=models.PositiveIntegerField(verbose_name="Valor menor a 240 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hrs_500",
            field=models.PositiveIntegerField(verbose_name="Valor menor a 500 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hrs_800",
            field=models.PositiveIntegerField(verbose_name="Valor menor a 800 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hrs_810",
            field=models.PositiveIntegerField(verbose_name="Valor mayor a 810 cc"),
        ),
    ]
