# Generated by Django 4.1.5 on 2023-02-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0011_alter_servicio_hrs_240_alter_servicio_hrs_500_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajador",
            name="tipo_trab",
            field=models.CharField(max_length=250, verbose_name="Clasificación"),
        ),
    ]
