# Generated by Django 4.1.5 on 2023-02-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0014_alter_servicio_tipo_sv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="desc_sv",
            field=models.TextField(verbose_name="Descripción Servicio"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="tipo_sv",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Tipo Servicio"
            ),
        ),
    ]
