# Generated by Django 4.1.5 on 2023-02-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0017_alter_servicio_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detalle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_servicio",
                    models.PositiveIntegerField(verbose_name="Precio servicio"),
                ),
                (
                    "id_fi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page.ficha_ingreso",
                        verbose_name="Número de Ficha",
                    ),
                ),
                (
                    "id_sv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page.servicio",
                        verbose_name="Número de servicio",
                    ),
                ),
            ],
        ),
    ]
