# Generated by Django 4.1.5 on 2023-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0018_detalle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="tipo_sv",
            field=models.CharField(
                choices=[
                    ("Mantencion", "Mantención"),
                    ("Ajuste", "Ajuste"),
                    ("Reemplazo", "Reemplazo"),
                    ("Reparacion", "Reparacion"),
                    ("Modificacion", "Modificacion"),
                    ("Revisión", "Revision"),
                ],
                default="Reparacion",
                max_length=250,
                verbose_name="Tipo Servicio",
            ),
        ),
    ]
