# Generated by Django 4.1.5 on 2023-02-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0019_alter_servicio_tipo_sv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="hrs_240",
            field=models.FloatField(verbose_name="Horas hasta 240 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hrs_500",
            field=models.FloatField(verbose_name="Horas hasta 500 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hrs_800",
            field=models.FloatField(verbose_name="Horas hasta 800 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="hrs_810",
            field=models.FloatField(verbose_name="Horas desde 810 cc"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="tipo_sv",
            field=models.CharField(
                choices=[
                    ("Mantencion", "Mantención"),
                    ("Ajuste", "Ajuste"),
                    ("Reemplazo", "Reemplazo"),
                    ("Reparacion", "Reparación"),
                    ("Modificacion", "Modificación"),
                    ("Revision", "Revisión"),
                ],
                default="Mantención",
                max_length=250,
                verbose_name="Tipo Servicio",
            ),
        ),
    ]
