# Generated by Django 4.1.5 on 2023-02-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0020_alter_servicio_hrs_240_alter_servicio_hrs_500_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="ficha_ingreso", name="total_fi",),
    ]
