# Generated by Django 4.1.5 on 2023-02-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0021_remove_ficha_ingreso_total_fi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="falla",
            name="hora_hh_f",
            field=models.IntegerField(verbose_name="Horas Hombre"),
        ),
    ]
