# Generated by Django 4.1.5 on 2023-02-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0022_alter_falla_hora_hh_f"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden_trabajo",
            name="total_fi",
            field=models.PositiveIntegerField(default=0, verbose_name="Total"),
        ),
    ]
