# Generated by Django 4.1.5 on 2023-02-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0023_orden_trabajo_total_fi"),
    ]

    operations = [
        migrations.RemoveField(model_name="ficha_ingreso", name="estado_fi",),
    ]
