# Generated by Django 4.1.5 on 2023-02-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0024_remove_ficha_ingreso_estado_fi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ficha_ingreso",
            name="observaciones_fi",
            field=models.TextField(verbose_name="Observaciones"),
        ),
    ]
