# Generated by Django 4.1.6 on 2023-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_alter_ficha_ingreso_observaciones_fi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='precio_servicio',
            field=models.IntegerField(verbose_name='Precio servicio'),
        ),
    ]
