# Generated by Django 4.1.5 on 2023-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0026_alter_detalle_precio_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha_ingreso",
            name="km_mill_fi",
            field=models.IntegerField(default=0, verbose_name="Kilometraje"),
        ),
        migrations.AddField(
            model_name="ficha_ingreso",
            name="mill_km_vh",
            field=models.CharField(
                choices=[("km", "Kilometros"), ("mill", "Millas")],
                default="Kilometros",
                max_length=50,
                verbose_name="Unidad de Medida",
            ),
        ),
    ]
