# Generated by Django 4.1.5 on 2023-02-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0027_ficha_ingreso_km_mill_fi_ficha_ingreso_mill_km_vh"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumos",
            name="codigo_is_externo",
            field=models.CharField(
                default="CXI-111111", max_length=150, verbose_name="Código externo"
            ),
        ),
        migrations.AddField(
            model_name="insumos",
            name="precio_is_unitario",
            field=models.IntegerField(default=1, verbose_name="Precio unitario"),
        ),
        migrations.AddField(
            model_name="insumos",
            name="precio_total",
            field=models.IntegerField(default=1, verbose_name="Precio"),
        ),
        migrations.AlterField(
            model_name="ficha_ingreso",
            name="mill_km_vh",
            field=models.CharField(
                choices=[("km", "Kilometros"), ("Millas", "Millas")],
                default="Kilometros",
                max_length=50,
                verbose_name="Unidad de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="mill_km_vh",
            field=models.CharField(
                choices=[("km", "Kilometros"), ("Millas", "Millas")],
                default="Kilometros",
                max_length=50,
                verbose_name="Unidad de Medida",
            ),
        ),
    ]
