# Generated by Django 4.1.5 on 2023-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0028_insumos_codigo_is_externo_insumos_precio_is_unitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="rut_cli",
            field=models.CharField(
                max_length=12, primary_key=True, serialize=False, verbose_name="Rut"
            ),
        ),
    ]
